### PR TITLE
docs: add some documentation in case some problems arise with poetry

### PR DESCRIPTION
**Pull request by jgimeno**

### CODE REVIEW

**Comment by Unique-Divine** [comment]
This is a tragedy because the colab notebook requires 3.7

**Comment by jgimeno** [comment]
Oh no! But I could not make it work with 3.7 at least in Mac M1. I can remove the part from .python-version but keep the update on the HACKING.md

**Review by Unique-Divine — COMMENTED** [review]
I use this shell function for it: 
```bash
clear_poetry() {
  echo "clearing .cache/pypoetry"
  rm -rf ~/.cache/pypoetry

  echo "clearing .venv"
  rm -rf .venv

  echo "clearing poetry.lock"
  rm -f poetry.lock

  echo "poetry cache clear pypi --all"
  poetry cache clear pypi --all
}
```

It gives you a fresh virtual environment with updated packages by force

**Comment by Unique-Divine** [comment]
> Oh no! But I could not make it work with 3.7 at least in Mac M1. I can remove the part from .python-version but keep the update on the HACKING.md

Can we try debugging the error you're encountering with an M1? What's the error message and environment setup?

**Comment by Unique-Divine** [comment]
Closing this at it arose from using `poetry` installed via `brew`

**Pull request closed without merging**
